;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-semi&comma
        c-indent-line-or-region
        electric-newline-and-maybe-indent
        hungry-delete-forward
        indent-for-tab-command
        kill-region
        org-cycle
        org-end-of-line
        org-kill-line
        org-self-insert-command
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        ))

(setq mc/cmds-to-run-once
      '(
        drag-stuff-right
        end-of-buffer
        helm-M-x
        helm-find-files
        smartparens-strict-mode
        ))
