;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        avy-goto-char
        c-electric-brace
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-indent-line-or-region
        delete-indentation
        electric-newline-and-maybe-indent
        gpolonkai/move-to-beginning-of-line
        gpolonkai/move-to-end-of-line
        hungry-delete-backward
        hungry-delete-forward
        indent-for-tab-command
        kill-region
        kill-sexp
        magit-status
        org-cycle
        org-end-of-line
        org-kill-line
        org-return
        org-self-insert-command
        org-space-key
        org-yank
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-kill-hybrid-sexp
        sp-kill-region
        sp-kill-word
        sp-remove-active-pair-overlay
        sp-unwrap-sexp
        toggle-char-case
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-move
        ace-mc-add-char
        ace-mc-add-multiple-cursors
        ace-mc-add-single-cursor
        ace-mc-do-keyboard-reset
        drag-stuff-right
        end-of-buffer
        helm-M-x
        helm-find-files
        smartparens-strict-mode
        suspend-frame
        yaml-electric-backspace
        ))
